// swift-tools-version: 6.0
import PackageDescription

// GameMaster core libraries.
//
// The pure-logic, fully testable core of GameMaster lives here as a local
// Swift package so that `swift test` (and CI) can exercise it without Xcode.
// The macOS app is an Xcode target (generated by XcodeGen from `project.yml`)
// that depends on these products.
//
// Dependency chain: GMModel ← GMSystem ← (GMRuntime, GMBottles, GMLaunch) ← GMApps.
// All targets build in Swift 6 language mode (strict concurrency).

let package = Package(
    name: "GameMasterCore",
    platforms: [
        .macOS("26.0"),
    ],
    products: [
        .library(name: "GMModel", targets: ["GMModel"]),
        .library(name: "GMSystem", targets: ["GMSystem"]),
        .library(name: "GMRuntime", targets: ["GMRuntime"]),
        .library(name: "GMBottles", targets: ["GMBottles"]),
        .library(name: "GMLaunch", targets: ["GMLaunch"]),
        .library(name: "GMApps", targets: ["GMApps"]),
    ],
    targets: [
        .target(
            name: "GMModel",
            path: "Sources/GMModel"
        ),
        .target(
            name: "GMSystem",
            dependencies: ["GMModel"],
            path: "Sources/GMSystem"
        ),
        .target(
            name: "GMRuntime",
            dependencies: ["GMModel", "GMSystem"],
            path: "Sources/GMRuntime",
            resources: [.process("Resources")]
        ),
        .target(
            name: "GMBottles",
            dependencies: ["GMModel", "GMSystem", "GMRuntime"],
            path: "Sources/GMBottles"
        ),
        .target(
            name: "GMLaunch",
            dependencies: ["GMModel", "GMSystem", "GMRuntime", "GMBottles"],
            path: "Sources/GMLaunch"
        ),
        .target(
            name: "GMApps",
            dependencies: ["GMModel", "GMSystem", "GMRuntime", "GMBottles", "GMLaunch"],
            path: "Sources/GMApps",
            resources: [.process("Resources")]
        ),
        .target(
            name: "GMTestSupport",
            dependencies: ["GMModel", "GMSystem"],
            path: "Sources/GMTestSupport"
        ),
        .testTarget(
            name: "GMModelTests",
            dependencies: ["GMModel"],
            path: "Tests/GMModelTests"
        ),
        .testTarget(
            name: "GMSystemTests",
            dependencies: ["GMSystem", "GMModel", "GMTestSupport"],
            path: "Tests/GMSystemTests"
        ),
        .testTarget(
            name: "GMRuntimeTests",
            dependencies: ["GMTestSupport", "GMRuntime", "GMSystem", "GMModel"],
            path: "Tests/GMRuntimeTests"
        ),
        .testTarget(
            name: "GMBottlesTests",
            dependencies: ["GMTestSupport", "GMBottles", "GMRuntime", "GMSystem", "GMModel"],
            path: "Tests/GMBottlesTests"
        ),
        .testTarget(
            name: "GMLaunchTests",
            dependencies: ["GMTestSupport", "GMLaunch", "GMBottles", "GMRuntime", "GMSystem", "GMModel"],
            path: "Tests/GMLaunchTests"
        ),
        .testTarget(
            name: "GMAppsTests",
            dependencies: ["GMTestSupport", "GMApps", "GMLaunch", "GMBottles", "GMRuntime", "GMSystem", "GMModel"],
            path: "Tests/GMAppsTests"
        ),
    ]
)
